# Generated by Django 3.2.6 on 2021-08-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_cricao',
            new_name='data_criacao',
        ),
    ]
